// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2sjtfnPqiuTiDPt-v3cAANOxZ4wCIJNY',
    appId: '1:64238607602:web:e33494cc06f62da890046b',
    messagingSenderId: '64238607602',
    projectId: 'smartpgto',
    authDomain: 'smartpgto.firebaseapp.com',
    storageBucket: 'smartpgto.appspot.com',
    measurementId: 'G-1P6FJ5CRJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWfLEeYCW4S03U8hbvJa90V9HMQa1kEQ',
    appId: '1:64238607602:android:1707591f19fa745c90046b',
    messagingSenderId: '64238607602',
    projectId: 'smartpgto',
    storageBucket: 'smartpgto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-duLfdJoEbGmu5MkL3wFZJkCSsalnPaE',
    appId: '1:64238607602:ios:7449b8d3bbfc0c4690046b',
    messagingSenderId: '64238607602',
    projectId: 'smartpgto',
    storageBucket: 'smartpgto.appspot.com',
    iosBundleId: 'com.example.sistemaPagamento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-duLfdJoEbGmu5MkL3wFZJkCSsalnPaE',
    appId: '1:64238607602:ios:7f8370c0bfa69a5390046b',
    messagingSenderId: '64238607602',
    projectId: 'smartpgto',
    storageBucket: 'smartpgto.appspot.com',
    iosBundleId: 'com.example.sistemaPagamento.RunnerTests',
  );
}
